### ISSUE TITLE
训练refine_model

### ISSUE THREAD

**Issue by Amy-214** [CV-Reimplementation/AEFNet-Reimplementation#1]
请问如何训练refine_model呀，训练时如何冻结net_G和net_M呢？

**Comment by xuhangc** [comment]
先训练Fusion然后通过更改参数再训练Refine，冻结权重发生在
https://github.com/CV-Reimplementation/AEFNet-Reimplementation/blob/183cf3abc7361d7f6dd0e2e382931b1b67f6da1b/models/Refine_model.py#L141
这一行左右。
